apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: <your-ns>
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: <your-ns>
  labels:
    run: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache