apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::964849360084:role/k8s-cluster-ng
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::964849360084:user/aasnitsky@pandologic.com
      username: aasnitsky
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/aavraham@pandologic.com
      username: aavraham
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/abalali@pandologic.com
      username: abalali
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ablech@pandologic.com
      username: ablech
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/acohen@pandologic.com
      username: acohen
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/alon.itach@mail.huji.ac.il
      username: alon.itach@
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ameiry@pandologic.com
      username: ameiry
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ayosian@pandologic.com
      username: ayosian
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/bginzburg@pandologic.com
      username: bginzburg
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/bklein@pandologic.com
      username: bklein
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/bracha.neuman@gmail.com
      username: bracha.n
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/cblau@pandologic.com
      username: cblau
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ecohen@pandologic.com
      username: ecohen
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/hcohen@pandologic.com
      username: hcohen
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/hdagan@pandologic.com
      username: hdagan
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ielia@pandologic.com
      username: ielia
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/itach.alon@gmail.com
      username: itach
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/itamir@pandologic.com
      username: itamir
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/kbonfield@pandologic.com
      username: kbonfield
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/lattal@pandologic.com
      username: lattal
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/lbaranes@pandologic.com
      username: lbaranes
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/melbaz@pandologic.com
      username: melbaz
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/myanin@pandologic.com
      username: myanin
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/nalpenidze@pandologic.com
      username: nalpenidze
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/nleibovitch@pandologic.com
      username: nleibovitch
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/oshitikov@pandologic.com
      username: oshitikov
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/oshtainfeld@pandologic.com
      username: oshtainfeld
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/pfidler@pandologic.com
      username: pfidler
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/rkaplan@pandologic.com
      username: rkaplan
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/rleshem@pandologic.com
      username: rleshem
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/rrabinovich@pandologic.com
      username: rrabinovich
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/rzadok@pandologic.com
      username: rzadok
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/scohen@pandologic.com
      username: scohen
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/szilbershtein@pandologic.com
      username: szilbershtein
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/tkoren@pandologic.com
      username: tkoren
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/tlevi@pandologic.com
      username: tlevi
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/tmotie@gmail.com
      username: tmotie
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/tschwartz@pandologic.com
      username: tschwartz
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/tyamin@pandologic.com
      username: tyamin
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ubar@pandologic.com
      username: ubar
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/wsalameh@pandologic.com
      username: wsalameh
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/ybaharav@pandologic.com
      username: ybaharav
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/yelmoalem@pandologic.com
      username: yelmoalem
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/yfidman@pandologic.com
      username: yfidman
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/yfridman@pandologic.com
      username: yfridman
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/yhadad@pandologic.com
      username: yhadad
      groups:
        - system:masters
    - userarn: arn:aws:iam::964849360084:user/k8s-test
      username: k8s-test
      groups:
        - system:masters
